artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rushin236/Datasets/raw/main/Sleep_Disorder/Sleep_Disorder.csv
  local_data_file: artifacts/data_ingestion/local_data.csv

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["local_data.csv"]

data_transform:
  root_dir: artifacts/data_transform
  preprocessor_dir: preprocessor
  preprocessor_file: preprocessor/preprocessor.pkl
  train_data_file: artifacts/data_transform/train_data.csv
  test_data_file: artifacts/data_transform/test_data.csv

model_build_evaluate:
  root_dir: artifacts/model_evaluation
  model_dir: model
  model_file: model/model.pkl
  train_data_file: artifacts/data_transform/train_data.csv
  test_data_file: artifacts/data_transform/test_data.csv
  model_results_file: artifacts/model_evaluation/model_evaluation.txt

prediction:
  model_file: model/model.pkl
  preprocessor_file: preprocessor/preprocessor.pkl
