artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rushin236/Datasets/raw/main/Sleep_Disorder/Sleep_Disorder.csv
  local_data_file: artifacts/data_ingestion/local_data.csv

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["local_data.csv"]
